### ISSUE TITLE
AttributeError: 'SlabDumpCommand' object has no attribute 'kmem_cache_node_offset_slabs_partial'

### ISSUE THREAD

**Issue by Polaris-Snowfall** [bata24/gef#57]
Your extension is excellent; it greatly facilitates my work. Recently, I encountered the following error when using the 'slab-dump' command. I have verified that the 'init_offset' method was indeed called before the error occurred. Since I am not very familiar with Python, I am not entirely sure about the cause of the error.

Unrelated to the parameters; the error occurs whenever 'slab-dump' is used.

gef> slab-dump kmalloc-128 -n -q

------------------------------- Exception raised -------------------------------
AttributeError: 'SlabDumpCommand' object has no attribute 'kmem_cache_node_offset_slabs_partial'
----------------------------- Detailed stacktrace ------------------------------
File "/root/.gdbinit-gef.py", line 60681, in init_offset()
    ->     self.kmem_cache_node_offset_slabs_full = self.kmem_cache_node_offset_slabs_partial + current_arch.ptrsize * 2
File "/root/.gdbinit-gef.py", line 61019, in slabwalk()
    ->     if self.init_offset(force=self.meta) is False:
File "/root/.gdbinit-gef.py", line 61072, in do_invoke()
    ->     self.slabwalk(args.cache_name, args.cpu)
File "/root/.gdbinit-gef.py", line 10346, in wrapper()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10456, in inner_f()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10384, in inner_f()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10296, in wrapper()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10266, in wrapper()
    ->     return f(self, args, **kwargs)
File "/root/.gdbinit-gef.py", line 12605, in invoke()
    ->     self.do_invoke(argv)
----------------------------- Last 10 GDB commands -----------------------------
  254  tele  0xffff8ee0de3f4200 16 --n
  255  tele  0xffff8ee0de3f4180 16 --n
  256  tele  0xffff8ee0de3f410 16 --n
  257  c
  258  tele 0xffff93b3de3f5140 0 --n
  259  tele 0xffff93b3de3f5140 9 --n
  260  tele 0xffff93b3de3f5100 9 --n
  261  tele 0xffff93b3de3f5100 16 --n
  262  tele 0xffff93b3de3f5100 80 --n
  263  slab-dump kmalloc-128 -n -q
----------------------------- Runtime environment ------------------------------
gdb:     12.1
python:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
OS:      Ubuntu 22.04.3 LTS
kernel:  Linux Polaris 5.15.90.1-microsoft-standard-WSL2 \#1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
qemu:    2.3.0
--------------------------------------------------------------------------------

Thanks a lot for creating this amazing extension!

**Comment by bata24** [comment]
Thank you for your reporting.
I understand and fixed what caused the error. Sorry for the indentation mistake in python.
```
@@ -60773,7 +60773,7 @@ class SlabDumpCommand(GenericCommand):
         else:
             if not self.quiet:
                 info("offsetof(kmem_cache_node, slabs_partial): Not found")
-                return
+            return
```

However, this only eliminates the cause of the exception. **I don't think the root cause has been fixed.**

----

Reaching above path means that `slabs_partial` of `struct kmem_cache_node` has not been detected.
```
    struct kmem_cache_node {
        raw_spinlock_t list_lock;
        struct list_head slabs_partial; <--- here
        struct list_head slabs_full;
        struct list_head slabs_free;
```

The memory structure should probably look like this.
```
0xffff9fa68129ec00|+0x0000|+000: 0x0000000000000000  <---- this is raw_spinlock_t
0xffff9fa68129ec08|+0x0008|+001: 0xffff9fa68129ec08  ->  [loop detected]  <---- slabs_partial.next
0xffff9fa68129ec10|+0x0010|+002: 0xffff9fa68129ec08  ->  [loop detected]  <---- slabs_partial.prev
0xffff9fa68129ec18|+0x0018|+003: 0xffff9fa68129ec18  ->  [loop detected]  <---- slabs_full.next
0xffff9fa68129ec20|+0x0020|+004: 0xffff9fa68129ec18  ->  [loop detected]  <---- slabs_full.prev
0xffff9fa68129ec28|+0x0028|+005: 0xffff9fa68129ec28  ->  [loop detected]  <---- slabs_free.next
0xffff9fa68129ec30|+0x0030|+006: 0xffff9fa68129ec28  ->  [loop detected]  <---- slabs_free.prev
0xffff9fa68129ec38|+0x0038|+007: 0x0000000000000000
0xffff9fa68129ec40|+0x0040|+008: 0x0000000000000000
```
GEF's heuristic detection algorithm detects 6 consecutive linked list structures.
(The reason why I do this is because `raw_spinlock_t` may not be 8 bytes depending on the environment.)

Since it is a fairly simple algorithm, it is unlikely that a detection error will occur here. It is possible that detection failed in an earlier phase.

Today, I was just fixing a bunch of other stuff , so it's possible that it's already been fixed.
I apologize for the inconvenience, but could you please try it and see if the same issue occurs with the latest version of GEF?

**Comment by bata24** [comment]
Also, if the problem persists, please let me know where I can get a complete set of qemu images for debugging (if available).
There are few samples of qemu images using SLAB (instead of SLUB), and I only have 4 environments, so I would appreciate your help.

**Comment by Polaris-Snowfall** [comment]
Thanks a lot for the quick response.I have updated GEF and tried again, but unfortunately, the issue still persists. In fact, I was working on completing https://github.com/teambi0s/InCTFi/tree/master/2021/Pwn/Kqueue, and the Handout directory contains the complete environment. 

ps: (Username: ctf, Password: kqueue)

```
gef> slab-dump 
[+] Wait for memory scan
[+] slab_caches: 0xffffffffb4869580
[+] __per_cpu_offset: 0xffffffffb46d26e0
[+] offsetof(kmem_cache, list): 0x60
[+] offsetof(kmem_cache, name): 0x58
[+] offsetof(kmem_cache, size): 0x14
[+] offsetof(kmem_cache, flags): 0x20
[+] offsetof(kmem_cache, num): 0x24
[+] offsetof(kmem_cache, gfporder): 0x28
[+] offsetof(kmem_cache, object_size): 0x74
[+] offsetof(kmem_cache, node): 0x98
[+] offsetof(kmem_cache, cpu_cache): 0x0
[+] offsetof(page, next): 0x8
[+] offsetof(page, freelist): 0x20
[+] offsetof(page, s_mem): 0x28
[+] offsetof(page, active): 0x30
[+] offsetof(kmem_cache_node, slabs_partial): Not found
                                                                                                                                                                                  
------------------------------- Exception raised -------------------------------
AttributeError: 'SlabDumpCommand' object has no attribute 'array_cache_offset_avail'
----------------------------- Detailed stacktrace ------------------------------
File "/root/.gdbinit-gef.py", line 60952, in walk_caches()
    ->     kmem_cache["array_cache"]["avail"] = u32(read_memory(kmem_cache["array_cache"]["address"] + self.array_cache_offset_avail, 4))
File "/root/.gdbinit-gef.py", line 61135, in slabwalk()
    ->     parsed_caches = self.walk_caches(target_names, cpu_idx)
File "/root/.gdbinit-gef.py", line 61170, in do_invoke()
    ->     self.slabwalk(args.cache_name, args.cpu)
File "/root/.gdbinit-gef.py", line 10346, in wrapper()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10456, in inner_f()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10384, in inner_f()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10296, in wrapper()
    ->     return f(*args, **kwargs)
File "/root/.gdbinit-gef.py", line 10266, in wrapper()
    ->     return f(self, args, **kwargs)
File "/root/.gdbinit-gef.py", line 12605, in invoke()
    ->     self.do_invoke(argv)
----------------------------- Last 10 GDB commands -----------------------------
  261  history
  262  c
  263  c
  264  c
  265  c
  266  c
  267  c
  268  c
  269  c
  270  slab-dump 
----------------------------- Runtime environment ------------------------------
gdb:     12.1
python:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
OS:      Ubuntu 22.04.3 LTS
kernel:  Linux Polaris 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
qemu:    2.3.0
--------------------------------------------------------------------------------

......

GEF:                    Last modified: 2024-01-04 23:13:35 SHA1: f3ccced891eed542f9f9554675e22d492070770e
```

**Comment by bata24** [comment]
Thank you for providing environmental information.
I think it was fixed. It now works correctly in my environment.

The cause was that padding due to alignment was not taken into account. It seems that this caused the offset detection of `kmem_cache->node` to fail, causing an error in subsequent processing.

----

Although it is not directly related to this problem, I thought it would be better to be able to omit unnecessary displays during the debugging process, so I added 3 options such as `--skip-full`.

**Comment by Polaris-Snowfall** [comment]
I tested the 'slab-dump' command along with the three newly added options, and they work well. Beautiful and tidy displays! By the way, I'd like to mention that the slab/slub structures displayed in the 'help slab/slub' command are so clear, helping me learn kernel memory management.

Thanks for your development and maintenance work on the extension.this fantastic tool should be known by everyone studying the kernel.
